"use client";

import { useState, useRef, useEffect } from "react";
import { Copy, CheckCircle2, Download, Eye, FileText, ChevronDown } from "lucide-react";
import TextDiffView from "./TextDiffView";
import { motion, AnimatePresence } from "framer-motion";
import Loader4 from "./ui/loader-4";
import { GlowingShadow } from "./ui/glowing-shadow";

interface ResultCardProps {
  originalText: string;
  text: string;
  isLoading: boolean;
}

export default function ResultCard({ originalText, text, isLoading }: ResultCardProps) {
  const [copied, setCopied] = useState(false);
  const [viewMode, setViewMode] = useState<"clean" | "diff">("clean");
  const [exportOpen, setExportOpen] = useState(false);
  const exportRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (exportRef.current && !exportRef.current.contains(event.target as Node)) {
        setExportOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  if (isLoading) {
    return (
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="w-full h-80 border border-gray-200 dark:border-gray-800 rounded-lg flex flex-col items-center justify-center bg-transparent overflow-hidden"
      >
        <Loader4 />
      </motion.div>
    );
  }

  if (!text) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = (format: "doc" | "txt") => {
    setExportOpen(false);

    if (format === "txt") {
      const content = `PARAPHRASED DOCUMENT\n\n${text}\n\n---\nGenerated by ParaphraseAI`;
      const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "Paraphrased_Result.txt";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);


    } else {
      const content = `
        <html xmlns:o="urn:schemas-microsoft-com:office:office"
              xmlns:w="urn:schemas-microsoft-com:office:word"
              xmlns="http://www.w3.org/TR/REC-html40">
        <head>
          <meta charset="utf-8">
          <meta name=ProgId content=Word.Document>
          <title>Paraphrased Document</title>
          <style>
            body { font-family: Arial, sans-serif; font-size: 12pt; margin: 1in; }
            p { line-height: 1.6; }
          </style>
        </head>
        <body>
          <h1>Paraphrased Document</h1>
          <p>${text.replace(/\n/g, "</p><p>")}</p>
          <p style="color:#888;font-size:10pt;">— Generated by ParaphraseAI</p>
        </body>
        </html>
      `.trim();
      const blob = new Blob([content], { type: "application/msword" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "Paraphrased_Result.doc";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

    }
  };

  return (
    <GlowingShadow className="w-full">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.4, type: "spring", bounce: 0.4 }}
        className="w-full flex flex-col gap-4 relative group"
      >
        <div className="absolute inset-0 bg-gradient-to-r from-blue-500/10 to-purple-500/10 dark:from-blue-500/20 dark:to-purple-500/20 rounded-xl blur-xl group-hover:blur-2xl transition-all duration-500 -z-10"></div>

      <div className="flex flex-col sm:flex-row justify-between sm:items-center gap-4 bg-white/10 dark:bg-black/20 backdrop-blur-xl p-4 rounded-t-xl border border-white/10 dark:border-white/5 relative z-50">
        <h3 className="text-lg font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-purple-600 dark:from-blue-400 dark:to-purple-400">
          Paraphrased Result
        </h3>
        <div className="flex flex-wrap gap-2">
          {/* View Mode Toggle */}
          <div className="flex bg-gray-100 dark:bg-gray-800 rounded-lg p-1">
            <button
              onClick={() => setViewMode("clean")}
              className={`px-3 py-1.5 text-sm rounded-md transition-all flex items-center gap-1 ${viewMode === "clean" ? "bg-white dark:bg-gray-700 shadow-sm text-blue-600 dark:text-blue-400 font-medium" : "text-gray-500 hover:text-gray-700 dark:hover:text-gray-300"}`}
            >
              <FileText size={14} /> Clean
            </button>
            <button
              onClick={() => setViewMode("diff")}
              className={`px-3 py-1.5 text-sm rounded-md transition-all flex items-center gap-1 ${viewMode === "diff" ? "bg-white dark:bg-gray-700 shadow-sm text-purple-600 dark:text-purple-400 font-medium" : "text-gray-500 hover:text-gray-700 dark:hover:text-gray-300"}`}
            >
              <Eye size={14} /> View Changes
            </button>
          </div>

          <div className="relative" ref={exportRef}>
            <button
              onClick={() => setExportOpen(!exportOpen)}
              className="flex items-center gap-2 px-3 py-2 text-sm font-medium text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 bg-gray-50 dark:bg-gray-800 rounded-lg hover:bg-blue-50 dark:hover:bg-blue-900/30 transition-all border border-transparent hover:border-blue-200 dark:hover:border-blue-800"
              title="Download Options"
            >
              <Download size={16} /> Export <ChevronDown size={14} />
            </button>

            <AnimatePresence>
              {exportOpen && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: 10 }}
                  className="absolute right-0 mt-2 w-36 bg-white dark:bg-gray-800 rounded-lg shadow-xl border border-gray-100 dark:border-gray-700 overflow-hidden z-20"
                >
                  <div className="flex flex-col py-1">
                    {/* ✅ Use onClick with blob download — no target="_blank" */}
                    <button
                      onClick={() => handleDownload("doc")}
                      className="block w-full text-left px-4 py-3 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 transition cursor-pointer"
                    >
                      Word (.doc)
                    </button>
                    <button
                      onClick={() => handleDownload("txt")}
                      className="block w-full text-left px-4 py-3 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 transition cursor-pointer"
                    >
                      Text (.txt)
                    </button>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-3 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors shadow-sm"
          >
            {copied ? <CheckCircle2 size={16} /> : <Copy size={16} />}
            {copied ? "Copied!" : "Copy"}
          </button>
        </div>
      </div>

      <div className="bg-white/10 dark:bg-black/20 backdrop-blur-xl rounded-b-xl border border-white/10 dark:border-white/5 overflow-hidden relative">
        <AnimatePresence mode="wait">
          {viewMode === "clean" ? (
            <motion.div
              key="clean"
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 10 }}
              className="w-full min-h-[16rem] p-6 text-gray-800 dark:text-gray-200 whitespace-pre-wrap leading-relaxed text-lg"
            >
              {text}
            </motion.div>
          ) : (
            <motion.div
              key="diff"
              initial={{ opacity: 0, x: 10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -10 }}
              className="p-6 text-lg"
            >
              <TextDiffView originalText={originalText} rewrittenText={text} />
            </motion.div>
          )}
        </AnimatePresence>
      </div>
      </motion.div>
    </GlowingShadow>
  );
}