export const phraseReplacements: Record<string, string[]> = {
  // Category A - HIGH RISK
  "furthermore": ["also", "on top of that", "beyond that", "what's more", "and"],
  "moreover": ["also", "in addition", "besides", "plus"],
  "additionally": ["also", "along with this", "as well", "too"],
  "utilize": ["use", "apply", "work with", "employ"],
  "utilization": ["use", "usage", "application", "handling"],
  "delve": ["explore", "examine", "look into", "investigate", "go over"],
  "delves": ["explores", "examines", "looks into", "investigates"],
  "delving": ["exploring", "examining", "looking into", "investigating"],
  "testament to": ["proof of", "evidence of", "shows", "demonstrates"],
  "pivotal": ["crucial", "key", "important", "major", "central"],
  "seamlessly": ["smoothly", "easily", "flawlessly", "effortlessly"],
  "groundbreaking": ["innovative", "new", "original", "pioneering"],
  "cutting-edge": ["advanced", "modern", "latest", "newest"],
  "it is important to note": ["note that", "importantly", "keep in mind", "remember"],
  "it is worth noting": ["note that", "importantly", "keep in mind", "remember"],
  "in conclusion": ["to sum up", "finally", "overall", "to wrap up"],
  "in summary": ["to sum up", "briefly", "overall", "to wrap up"],
  "in today's rapidly evolving": ["nowadays", "today", "currently", "these days"],
  "in the realm of": ["in", "within", "about", "regarding"],
  "as previously mentioned": ["as mentioned", "as stated earlier", "we noted earlier"],
  "it goes without saying": ["clearly", "obviously", "of course"],
  "needless to say": ["clearly", "obviously", "of course"],
  "last but not least": ["finally", "lastly", "and finally"],

  // Category B - MEDIUM RISK
  "significant": ["important", "major", "meaningful", "notable"],
  "significantly": ["greatly", "much", "considerably", "notably"],
  "comprehensive": ["complete", "thorough", "full", "detailed"],
  "comprehensively": ["completely", "thoroughly", "fully", "in detail"],
  "robust": ["strong", "solid", "tough", "durable"],
  "enhance": ["improve", "boost", "increase", "better"],
  "leverage": ["use", "take advantage of", "rely on", "make use of"],
  "innovative": ["new", "creative", "original", "fresh"],
  "paradigm": ["model", "pattern", "example", "standard"],
  "holistic": ["complete", "whole", "comprehensive", "full"],
  "streamline": ["simplify", "make easier", "smooth", "organize"],
  "scalable": ["adaptable", "flexible", "expandable", "growable"],
  "actionable": ["practical", "useful", "doable", "applicable"],
  "synergy": ["collaboration", "teamwork", "cooperation", "combined effort"],
  "ecosystem": ["environment", "system", "network", "community"]
};